# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapUnitsPerPixel
                                 A QGIS plugin
 Displays the current pixel size of the map in the status bar.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-26
        copyright            : (C) 2022 by Andreas Steffens (Geo Daten Service GmbH)
        email                : a.steffens@gds-team.de
 ***************************************************************************/

 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Andreas Steffens'
__date__ = '26/12/2022'
__copyright__ = 'Copyright 2022, Andreas Steffens (GDS Geo Daten Service GmbH)'

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapUnitsPerPixel class from file map_units_per_pixel.py.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_units_per_pixel import MapUnitsPerPixel
    return MapUnitsPerPixel(iface)
